language: minimal


install:
  - docker pull biilal1999/gamestore
  - docker images


script:
  - docker run -t -v `pwd`:/test biilal1999/gamestore:latest


notifications:
   email:
      on_success: never
      on_failure: never

