name: githubActions
on: [push]
jobs: 
   build:
      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby version
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7.2

      - name: Build the image 
        run: docker build -t gamedocker .

      - name: Run tests
        run: docker run -t -v `pwd`:/test gamedocker:latest

      - name: Install deps
        run: bundle install

      - name: Run test
        run: rake test


