name: githubActions
on: [push]
jobs: 
   check-bats-version:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2

      - name: Build the image 
        run: docker build -t GameDocker .

      - name: Run tests
        run: docker run -t -v `pwd`:/test GameDocker:latest


