name: githubActions
on: [push]
jobs: 
   build:
      runs-on: ubuntu-latest

      steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.TOK }}

      - name: Download the image from Docker Hub 
        run: docker pull biilal1999/gamestore:latest .

      - name: List the images
        run: docker images

      - name: Run tests
        run: docker run -t -v `pwd`:/test biilal1999/gamestore:latest

      - name: Publish to GitHub Container Registry
        run: docker push biilal1999/gamestore:latest

