name: github-docker-actions
on: [push]
jobs: 
   check-bats-version:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.TOK }}

      - name: Build the image 
        run: docker build -t ghcr.io/biilal1999/gamestore/normal:latest .

      - name: Publish to GitHub Container Registry
        run: docker push ghcr.io/biilal1999/gamestore/normal:latest

