name: githubActions
on: [push]
jobs: 
   build:
      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.TOK }}

      - name: Build the image 
        run: docker build -t ghcr.io/biilal1999/gamestore:latest .

      - name: Run tests
        run: docker run -t -v `pwd`:/test ghcr.io/biilal1999/gamestore:latest

      - name: Publish to GitHub Container Registry
        run: docker push ghcr.io/biilal1999/gamestore:latest


